Module2 task1
htmlacademy-javascript/1720461-kekstagram-26 pull request #2
Opened 2022-06-06 18:43 UTC by bazarovstas

Добавлены функции getRandomNumber() и hasAllowedStringLength()
-getRandomNumber() для генерации случайного числа из заданного диапазона (мин, макс), возвращает число
-hasAllowedStringLength() для подсчета максимальной длины строки, возвращает логическое значение

2022-06-06 21:27 UTC, Zakamsky requested changes
В целом неплохо, я бы даже принял, но не могу допустить лог как часть функциональности функции...
Ну и приведение типа я бы очень настоятельно советовал заменить на условие.
НО в остальном материал усвоен достаточно хорошо.

2022-06-06 21:27 UTC, Zakamsky commented on js/main.js
> +  const stringLength = String(string).length;
Приведение к типу слегка помогает нам облениться но смотри какие классные артефакты можно словить:
![image](https://user-images.githubusercontent.com/35491086/172251012-6a0cd8a3-069b-4c5f-a0c3-69c5d10b6385.png)

2022-06-07 06:46 UTC, bazarovstas commented on js/main.js
> +  return console.log('Введены отрицательные числа');
Убрал return, заменил вывод в консоль выводом ошибки throw new Error

2022-06-07 08:23 UTC, bazarovstas commented on js/main.js
> +  const stringLength = String(string).length;
Я не пробовал подставлять объекты, поправил на условие)
Интересно, а для чего тогда может пригодиться приведение типов, если теоретически можно много где вставить массив и объект вместо строки или числа?

2022-06-07 08:31 UTC, bazarovstas commented on js/main.js
> +  return false;
Убрал условие, прописал его сразу в return

2022-06-07 20:23 UTC, Zakamsky approved these changes
В целом одна ошибка еще осталась, но это опциальная функциональность, давай не будем затягивать, т.к. обязательная часть исполнена на отлично.

2022-06-07 20:24 UTC, merged

2022-06-08 06:23 UTC, bazarovstas commented on js/main.js
> +  return false;
Поправил и изменил немного функцию, теперь, если получена строка и длина подходит, то будет возвращен true
![image](https://user-images.githubusercontent.com/54740381/172545028-3927c49d-34fd-49c6-9277-5473e6aeb312.png)
если получена строка и длина НЕ подходит, то будет возвращен false
![image](https://user-images.githubusercontent.com/54740381/172545142-63ec3f19-7599-42ce-925e-086a4f413b32.png)
и если получена НЕ строка то длина не важна, и будет возвращен error
![image](https://user-images.githubusercontent.com/54740381/172545398-e8321ddf-f56d-45bd-b28a-9208ad632166.png)

2022-06-08 10:19 UTC, Zakamsky commented on js/main.js
> +  return false;
Вот теперь просто отлично всё!

2022-06-08 10:22 UTC, Zakamsky commented on js/main.js
> +  const stringLength = String(string).length;
Приведение типов может пригодиться для разных случаев когда у нас есть число, но мы хотим с ним работать как со строкой, или наоборот.
В большинстве случаев js сам приведет типы, но это может быть иногда совсем не тот результат который нам нужен.
Еще частный случай - когда мы получаем в результате сложных вычислений (сложнее простого сравнения) число и если оно положительное хотим выполнить какое то действие, - мы можем привести такое число к логическому значению и опираться уже на true/false