Module4 task1
htmlacademy-javascript/1720461-kekstagram-26 pull request #3
Opened 2022-06-16 20:05 UTC by bazarovstas

2022-06-17 13:10 UTC, Zakamsky requested changes
Немного не до конца понятно условие, уверен что если бы оно было описано понятнее, ты бы сразу сделал все корректно.

2022-06-17 13:10 UTC, Zakamsky commented on js/main.js
> +Все комментарии генерируются случайным образом. Пример описания объекта с комментарием:
вот тут давай обратим внимание на начало фразы:
> comments, массив объектов
Получается что это не один комментарий, а несколько.  Мы можем руками установить что их будет два, или три, а можем рандомное кол-во раз вызвать функцию создания комментария.
Второй вариант кажется поинтереснее но могут быть сложности с уникальным айди.
Можно обсудить это в чате.

2022-06-18 13:19 UTC, bazarovstas commented on js/main.js
> +Все комментарии генерируются случайным образом. Пример описания объекта с комментарием:
Исправил, добавил счетчик который считает количество вызовов функции создания комментариев, и в свойство id подставляет значение из счетчика, таким образом id всегда уникальный. изменил функции, теперь первая функция создает комментарии, вторая создает 1 элемент массива и добавляет туда эти комментарии, третья повторяет процесс необходимое количество раз.

2022-06-19 11:19 UTC, Zakamsky approved these changes
Теперь мы получаем нужный по ТЗ результат. код немного запутанный, но с опытом все придет! Показал в комментариях пару оптимизаций.
Апрув!
Давай посмотрим что мы теперь можем сделать с этими данными.

2022-06-19 11:19 UTC, Zakamsky commented on js/main.js
> +    counterForID += 1;
строки 88 и 93 можно оптимизировать при помощи пост-инкремента:
```js
{
  id: counterForID++
}
```
так оператиор сперва вернет значение `counterForID` оно будет присвоено в `id` и после увеличено на 1.
посомтри в чате мы обсуждали как это работает и чем отличается `++i` и `i++`

2022-06-19 11:19 UTC, Zakamsky commented on js/main.js
> +    commentsArray = [];
на 114й строке мы меняем неочевидным способом переменную в глобальном скопе, и потом, в 116й строке, как бы сбрасываем ее.
мы могли бы упростить задачу ограничив область видимости переменной:
```
for (let i = 1; i <= count; i++) {
  let commentsArray = [];
  createCommentsForOnePicture();
  generatedPicturesArray.push(createOnePictureItem(i));
}
```
т.е. мы создаем и используем переменную непосредственно в каждой итерации цикла.

2022-06-19 11:19 UTC, merged

2022-06-26 14:50 UTC, bazarovstas commented on js/main.js
> +    commentsArray = [];
Исправлено

2022-06-26 14:50 UTC, bazarovstas commented on js/main.js
> +    counterForID += 1;
Исправил