Правда или действие (часть 1)
htmlacademy-javascript/1720461-kekstagram-26 pull request #7
Opened 2022-07-14 16:20 UTC by bazarovstas

---
:mortar_board: [Правда или действие (часть 1)](https://up.htmlacademy.ru/javascript/26/user/1720461/tasks/15)

:boom: https://htmlacademy-javascript.github.io/1720461-kekstagram-26/7/

2022-07-14 22:31 UTC, Zakamsky requested changes
Надеюсь помог комментариями.
Давай поправим.

код в функции проверки хештегов довольно криповенький, но он работает, за исключением цикла.
можно все же сделать несколько простых функций и разные валидации, или немного упростить эту, например сделав плоские проверки.
проверили что то одно - фалс? вернули фалс и все.
после возврата `else` не нужен - функция остановится.

2022-07-14 22:31 UTC, Zakamsky commented on js/form.js
> +    document.removeEventListener('keydown', onOverlayEscKeydown); // убираем обработчик на закрытие окна по кнопке Esc
нам бы тут точно так же обработчик клика прибить, а то вона чего:  

![image](https://user-images.githubusercontent.com/35491086/179096857-c493144a-999c-4ab8-98bf-f29f0d8390e7.png)  
утекает память...

2022-07-14 22:31 UTC, Zakamsky commented on js/form.js
> +      if (elementToCompare === hashTagsArray[i]) { // если в массиве нашлись одинаковые элементы...
хм....
проверяем:

![image](https://user-images.githubusercontent.com/35491086/179098085-e98fd541-1eab-47d1-b55c-d844a2d8734e.png)

пока работает, а еще раз:

![image](https://user-images.githubusercontent.com/35491086/179098174-3e263ed7-4132-4669-b4bf-47e3d0ba32b3.png)
![image](https://user-images.githubusercontent.com/35491086/179098166-cf0f3533-31ea-4b31-838d-0a406792d26e.png)

ага, причина в том что мы сравниваем только первый элемент на уникальность. а дальше хоть трава не расти.
получается что для работы обычными циклами нам придется прогонять цикл для каждого элемента массива О_о хорошо что их по тз максимум пять.

я скину вам в чат как проверить уникальность элементов массива с помощью `Set`

2022-07-14 22:31 UTC, Zakamsky commented on js/form.js
> +      closeModal();
можно тут добавить еще один if - и вызывать `closeModal()` только если `evt.target` не равно инпутам в форме.
(выведи в консоль `evt.target` вместо `closeModal()` и поклацай ескейп в разных местах проекта)

2022-07-15 09:41 UTC, bazarovstas commented on js/form.js
> +    document.removeEventListener('keydown', onOverlayEscKeydown); // убираем обработчик на закрытие окна по кнопке Esc
Поправил

2022-07-15 10:21 UTC, bazarovstas commented on js/form.js
> +      closeModal();
Поправил

2022-07-15 11:59 UTC, bazarovstas commented on js/form.js
> +      if (elementToCompare === hashTagsArray[i]) { // если в массиве нашлись одинаковые элементы...
Поправил, теперь валидация идет через Set

2022-07-15 12:01 UTC, bazarovstas commented
Сделал из одной большой криповой функции три функции поменьше, надеюсь норм теперь)

2022-07-15 18:48 UTC, Zakamsky approved these changes
Вот теперь отлично все.

И валидация стала намного лаконичнее и читаемее. А еще, что важно, сообщения пользователю стали более информативными.

малюсенькое замечание - если к строке перед всеми проверками применить `.trim()` то не будет выскакивать сообщение из за одного пробела пока пользователь только собирается вводить новый хештег.

2022-07-15 18:48 UTC, merged

2022-07-16 07:17 UTC, bazarovstas commented
> Вот теперь отлично все.
> 
> И валидация стала намного лаконичнее и читаемее. А еще, что важно, сообщения пользователю стали более информативными.
> 
> малюсенькое замечание - если к строке перед всеми проверками применить `.trim()` то не будет выскакивать сообщение из за одного пробела пока пользователь только собирается вводить новый хештег.

Добавил метод .trim() в функции валидации хештегов